server:
  port: 9000

spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/court?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    show-sql: true

predict:
  python-interpreter-path: D:\\Miniconda2\\envs\\complaint-predict\\python
  predict-python-file-path: C:\\Users\\Yang\\PycharmProjects\\complaint-predict\\test.py
  json-file-path: C:\\Users\\Yang\\PycharmProjects\\complaint-predict\\data.json


# 日志
logging:
  level:
    cn.zero4eva.complaint.manage: INFO

